### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by mominurr** [thicccat688/selenium-recaptcha-solver#18]
give me this error when I am running your example code. why give me this error? please give me a solution.

Traceback (most recent call last):
  File "d:\Web Scraping Project\visa.vfsglobal.com\test.py", line 30, in <module>
    solver.click_recaptcha_v2(iframe=recaptcha_iframe)
  File "C:\Users\Mominur Rahman\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium_recaptcha_solver\solver.py", line 87, in click_recaptcha_v2
    self.solve_recaptcha_v2_challenge(iframe=captcha_challenge)
  File "C:\Users\Mominur Rahman\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium_recaptcha_solver\solver.py", line 113, in solve_recaptcha_v2_challenge
    self._solve_audio_challenge()
  File "C:\Users\Mominur Rahman\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium_recaptcha_solver\solver.py", line 181, in _solve_audio_challenge
    AudioSegment.from_mp3(mp3_file).export(wav_file, format='wav')
  File "C:\Users\Mominur Rahman\AppData\Local\Programs\Python\Python310\lib\site-packages\pydub\audio_segment.py", line 796, in from_mp3       
    return cls.from_file(file, 'mp3', parameters=parameters)
  File "C:\Users\Mominur Rahman\AppData\Local\Programs\Python\Python310\lib\site-packages\pydub\audio_segment.py", line 728, in from_file      
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
  File "C:\Users\Mominur Rahman\AppData\Local\Programs\Python\Python310\lib\site-packages\pydub\utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "C:\Users\Mominur Rahman\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Mominur Rahman\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by thicccat688** [comment]
Hello again,

I looked into your issue and found this thread that explains the problem in detail: https://stackoverflow.com/questions/22284461/pydub-windowserror-error-2-the-system-can-not-find-the-file-specified

The accepted answer should have everything you need to fix the error. Maybe also look into reinstalling FFmpeg if it was improperly installed.

Have a nice day!
